const preguntas = [
    { id: "1", texto: "Me gusta soñar despierto" },
    { id: "2", texto: "Soy una persona competitiva" },
    { id: "3", texto: "Las variedades de sonido y color son deliciosas (las disfruto)" },
    { id: "4", texto: "Mi mundo interior es muy real para mí" },
    { id: "5", texto: "Soy un pensador independiente (me gusta pensar por mi mismo, sin que me digan cómo hacerlo)" },
    { id: "6", texto: "Siento intensamente las emociones de otras personas" },
    { id: "7", texto: "Si una actividad es físicamente extenuante la encuentro satisfactoria" },
    { id: "8", texto: "Mirar el arte es una experiencia totalmente absorbente" },
    { id: "9", texto: "Me preocupo mucho" },
    { id: "10", texto: "Me encanta estar en movimiento" },
    { id: "11", texto: "Me pone triste ver a una persona solitaria en un grupo" },
    { id: "12", texto: "Puedo tomar conceptos difíciles y traducirlos en algo más entendible" },
    { id: "13", texto: "Obtengo un gran goce de las obras de arte de otros" },
    { id: "14", texto: "Cuando me aburro empiezo a soñar despierto" },
    { id: "15", texto: "Cuando tengo mucha energía quiero hacer algo realmente físico" },
    { id: "16", texto: "Cuestiono todo –cómo trabajan las cosas, qué significan las cosas, por qué las cosas son como son-" },
    { id: "17", texto: "Puedo sentirme tan feliz que quiero reír y llorar al mismo tiempo" },
    { id: "18", texto: "Tengo más energía que la mayoría de personas de mi edad" },
    { id: "19", texto: "Soy capaz de formar ideas nuevas relacionando cosas diferentes" },
    { id: "20", texto: "Algunas veces actúo como si fuese una persona diferente" },
    { id: "21", texto: "Entre más tiempo tengo que permanecer sentado, más inquieto me pongo" },
    { id: "22", texto: "Las cosas que imagino en mi mente son tan vívidas como las cosas reales" },
    { id: "23", texto: "Observo y analizo todo" },
    { id: "24", texto: "Me descubro a mí mismo mezclando verdad y fantasía en mis pensamientos" },
    { id: "25", texto: "Las teorías echan a andar mi mente (me gusta \"filosofar\")" },
    { id: "26", texto: "Tengo fuertes sentimientos de alegría, enfado, emoción y desesperación" },
    { id: "27", texto: "Siento la música en todo mi cuerpo entero" },
    { id: "28", texto: "Disfruto de exagerar la realidad" },
    { id: "29", texto: "Siento que mi cuerpo está en movimiento constante" },
    { id: "30", texto: "Me encanta resolver problemas y desarrollar nuevos conceptos" },
    { id: "31", texto: "Me preocupo profundamente por los demás" },
    { id: "32", texto: "Disfruto con los colores, formas y texturas de las cosas más de lo que las demás personas lo hacen" },
    { id: "33", texto: "Creo que las muñecas, los animales de peluche o los personajes de los libros están vivos y tienen sentimientos" },
    { id: "34", texto: "Las palabras y los sonidos crean imágenes en mi mente" },
    { id: "35", texto: "Mis emociones fuertes me hacen llorar" },
    { id: "36", texto: "Me gusta hurgar más allá de la superficie de las cosas (conocer a fondo)" },
    { id: "37", texto: "Soy movido por la belleza de la naturaleza" },
    { id: "38", texto: "No siento el color, las formas o las texturas tanto como otras personas" },
    { id: "39", texto: "Cuando estoy nervioso necesito hacer algo físico" },
    { id: "40", texto: "Trato de analizar mis pensamientos y acciones" },
    { id: "41", texto: "Puedo sentir una mezcla de emociones diferentes a la vez" },
    { id: "42", texto: "Yo soy el tipo de persona que tiene que estar activa –caminando, limpiando, organizando, haciendo algo-" },
    { id: "43", texto: "Me gusta jugar con mis ideas y tratar de pensar en cómo hacerlas útiles o llevarlas a la práctica" },
    { id: "44", texto: "Soy una persona no emocional (fría, que demuestra poco sus sentimientos)" },
    { id: "45", texto: "Disfruto las sensaciones de los colores, formas y diseños" },
    { id: "46", texto: "La diferencia de aromas me resulta interesante" },
    { id: "47", texto: "Tengo talento para la fantasía" },
    { id: "48", texto: "Me encanta escuchar los sonidos de la naturaleza" },
    { id: "49", texto: "Tomo todo a pecho (todo lo que me sucede me afecta mucho)" },
    { id: "50", texto: "Desarrollo una actividad física intensa, por ej. juegos de velocidad y deportes" }
]

export default preguntas;
