const preguntas = [
    { id: "1", texto: "Normalmente me divierto y disfruto de la vida" },
    { id: "2", texto: "Confío en la gente que conozco" },
    { id: "3", texto: "No soy minucioso con los detalles pequeños" },
    { id: "4", texto: "No puedo decidir qué tipo de persona quiero ser" },
    { id: "5", texto: "Muestro mis sentimientos a todo el mundo" },
    { id: "6", texto: "Dejo que los demás tomen decisiones importantes por mí" },
    { id: "7", texto: "Me preocupo si oigo malas noticias sobre alguien que conozco" },
    { id: "8", texto: "Ceder a algunos de mis impulsos me causa problemas" },
    { id: "9", texto: "Mucha gente que conozco me envidia" },
    { id: "10", texto: "Doy mi opinión general sobre las cosas y no me preocupo por los detalles" },
    { id: "11", texto: "Nunca me han detenido" },
    { id: "12", texto: "La gente cree que soy frío y distante" },
    { id: "13", texto: "Me meto en relaciones muy intensas pero poco duraderas" },
    { id: "14", texto: "La mayoría de la gente es justa y honesta conmigo" },
    { id: "15", texto: "La gente tiene una gran opinión sobre mí" },
    { id: "16", texto: "Me siento molesto o fuera de lugar en situaciones sociales" },
    { id: "17", texto: "Me siento fácilmente influido por lo que me rodea" },
    { id: "18", texto: "Normalmente me siento mal cuando hago daño o molesto a alguien" },
    { id: "19", texto: "Me resulta muy difícil tirar las cosas" },
    { id: "20", texto: "A veces he rechazado un trabajo, incluso aunque estuviera esperándolo" },
    { id: "21", texto: "Cuando me alaban o critican manifiesto mi reacción a los demás" },
    { id: "22", texto: "Uso a la gente para lograr lo que quiero" },
    { id: "23", texto: "Paso demasiado tiempo tratando de hacer las cosas perfectamente" },
    { id: "24", texto: "A menudo, la gente se ríe de mí, a mis espaldas" },
    { id: "25", texto: "Nunca he amenazado con suicidarme, ni me he autolesionado a propósito" },
    { id: "26", texto: "Mis sentimientos son como el tiempo, siempre están cambiando" },
    { id: "27", texto: "Para evitar críticas prefiero trabajar solo" },
    { id: "28", texto: "Me gusta vestirme para destacar entre la gente" },
    { id: "29", texto: "Mentiría o haría trampas para lograr mis propósitos" },
    { id: "30", texto: "Soy más supersticioso que la mayoría de la gente" },
    { id: "31", texto: "Tengo poco o ningún deseo de mantener relaciones sexuales" },
    { id: "32", texto: "La gente cree que soy demasiado estricto con las reglas y normas" },
    { id: "33", texto: "Generalmente me siento incómodo o desvalido si estoy solo" },
    { id: "34", texto: "No me gusta relacionarme con gente hasta que no estoy seguro de que les gusto" },
    { id: "35", texto: "No me gusta ser el centro de atención" },
    { id: "36", texto: "Creo que mi cónyuge (amante) me puede ser infiel" },
    { id: "37", texto: "La gente piensa que tengo muy alto concepto de mí mismo" },
    { id: "38", texto: "Cuido mucho lo que les digo a los demás sobre mí" },
    { id: "39", texto: "Me preocupa mucho no gustar a la gente" },
    { id: "40", texto: "A menudo me siento vacío por dentro" },
    { id: "41", texto: "Trabajo tanto que no tengo tiempo para nada más" },
    { id: "42", texto: "Me da miedo que me dejen solo y tener que cuidar de mí mismo" },
    { id: "43", texto: "Tengo ataques de ira o enfado" },
    { id: "44", texto: "Tengo fama de que me gusta flirtear" },
    { id: "45", texto: "Me siento muy unido a gente que acabo de conocer" },
    { id: "46", texto: "Prefiero las actividades que pueda hacer por mí mismo" },
    { id: "47", texto: "Pierdo los estribos y me meto en peleas" },
    { id: "48", texto: "La gente piensa que soy tacaño con mi dinero" },
    { id: "49", texto: "Con frecuencia busco consejos o recomendaciones sobre decisiones de la vida cotidiana" },
    { id: "50", texto: "Para caer bien a la gente me ofrezco a realizar tareas desagradables" },
    { id: "51", texto: "Tengo miedo a ponerme en ridículo ante gente conocida" },
    { id: "52", texto: "A menudo confundo objetos o sombras con gente" },
    { id: "53", texto: "Soy muy emocional y caprichoso" },
    { id: "54", texto: "Me resulta difícil acostumbrarme a hacer cosas nuevas" },
    { id: "55", texto: "Sueño con ser famoso" },
    { id: "56", texto: "Me arriesgo y hago cosas temerarias" },
    { id: "57", texto: "Todo el mundo necesita uno o dos amigos para ser feliz" },
    { id: "58", texto: "Descubro amenazas ocultas en lo que me dicen algunas personas" },
    { id: "59", texto: "Normalmente trato de que la gente haga las cosas a mi manera" },
    { id: "60", texto: "Cuando estoy estresado las cosas que me rodean no me parecen reales" },
    { id: "61", texto: "Me enfado cuando la gente no quiere hacer lo que le pido" },
    { id: "62", texto: "Cuando finaliza una relación, tengo que empezar otra rápidamente" },
    { id: "63", texto: "Evito las actividades que no me resulten familiares para no sentirme molesto tratando de hacerlas" },
    { id: "64", texto: "A la gente le resulta difícil saber claramente qué estoy diciendo" },
    { id: "65", texto: "Prefiero asociarme con gente de talento" },
    { id: "66", texto: "He sido víctima de ataques injustos sobre mi carácter o mi reputación" },
    { id: "67", texto: "No suelo mostrar emoción" },
    { id: "68", texto: "Hago cosas para que la gente me admire" },
    { id: "69", texto: "Suelo ser capaz de iniciar mis propios proyectos" },
    { id: "70", texto: "La gente piensa que soy extraño o excéntrico" },
    { id: "71", texto: "Me siento cómodo en situaciones sociales" },
    { id: "72", texto: "Mantengo rencores contra la gente durante años" },
    { id: "73", texto: "Me resulta difícil no estar de acuerdo con las personas de las que dependo" },
    { id: "74", texto: "Me resulta difícil no meterme en líos" },
    { id: "75", texto: "Llego al extremo para evitar que la gente me deje" },
    { id: "76", texto: "Cuando conozco a alguien no hablo mucho" },
    { id: "77", texto: "Tengo amigos íntimos" },
  ]
  
export default preguntas;
  